# Generated by Django 4.1.7 on 2023-03-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triangle', '0003_alter_logs_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='data',
        ),
        migrations.AddField(
            model_name='logs',
            name='get_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logs',
            name='post_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
